// Copyright (c) avijit bhattacharjee
name: Copyright Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  copyright_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run copyright checks
        run: build-scripts/copyright_check.sh
