name: Execute Java Classes

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Execution_Java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with javac
        run: java -version

      - name: Compile Java Classes
        run: |
          java Sorting
